baseURL = "https://hatsusixty.github.io"
languageCode = "en-us"
title = "Hatsu Sixty's Website"
theme = "hatsusixtys-theme"

[[menu.main]]
name = "Home"
url = ""
weight = 1

[[menu.main]]
name = "Wiki"
url = "wiki/useful/"
weight = 2

[[menu.main]]
name = "Projects"
url = "projects/"
weight = 3

[[menu.main]]
name = "Fun Stuff!"
url = "fun_stuff/"
weight = 4

[[menu.main]]
name = "New Content"
url = "new_content/"
weight = 5

[[menu.main]]
name = "About"
url = "about/"
weight = 6